"""Offline, escaped HTML dossier viewer. No remote scripts, fonts or model requests."""
from html import escape

def render(snapshot,plan,catalog,evaluation):
    esc=lambda s:escape(str(s if s is not None else '未确定'),quote=True)
    def ul(values):return '<ul>'+''.join('<li>'+esc(v)+'</li>' for v in values)+'</ul>'
    sources={s.evidence_id:s for s in plan.sources}
    assets={r['id']:r for r in catalog['records']}
    results={r['hypothesis_id']:r for r in evaluation['items']}
    cards=[]
    for h in plan.hypotheses:
        gate=results[h.hypothesis_id];e=h.experiment
        links=[]
        for link in h.links:
            s=sources[link.evidence_id]
            labels={'support':'支持待检验假设','oppose':'反对 / 重要反证','context':'背景与市场信号'}
            links.append(f'''<div class="evidence {esc(link.stance)}"><b>{labels[link.stance]} · {esc(s.evidence_id)} · {esc(s.kind)}</b><p>{esc(link.interpretation)}</p><p>{esc(s.summary)}</p><a href="{esc(s.url)}" target="_blank" rel="noopener noreferrer">{esc(s.title)}</a><p class="meta">位置：{esc(s.locator)} · 来源家族：{esc(s.family)} · 核对记录：{esc(s.checked_on)}</p><p>局限：{esc('；'.join(s.limitations))}</p><p>人工来源审查：{esc(s.reviewed_by)}；{esc(s.review_note)}</p><p>反证处理：{esc(link.contradiction_response)} · 审查人：{esc(link.response_reviewer)}</p></div>''')
        comps=''.join(f'<tr><td>{esc(assets[i]["company"])}</td><td>{esc(assets[i]["asset"])}</td><td>{esc(assets[i]["event"])}</td><td>{esc(assets[i]["economics_usd"])}</td></tr>' for i in h.competitor_asset_ids)
        gaps=''.join(f'<li><code>{esc(g["code"])}</code> — {esc(g["required"])}</li>' for g in gate['gaps'])
        expfields=[('实验系统',e.system),('独立生物学单位',e.biological_unit),('比较',e.comparison),('主要终点',e.primary_endpoint),('样本量',e.sample_size),('样本量依据',e.sample_size_basis),('分析计划',e.analysis_plan),('随机化与盲法',e.randomization_blinding),('有意义效应',e.meaningful_effect),('协议版本',e.protocol_ref),('实验负责人',e.owner),('材料可用性',e.material_access_ref),('数据用途权利',e.data_rights_ref),('预算',str(e.budget_amount)+' '+str(e.currency) if e.budget_amount else None),('预算授权',e.budget_authorization_ref)]
        cards.append(f'''<article class="candidate" data-search="{esc(h.title+' '+h.target+' '+h.indication)}"><div class="card-head"><span class="eyebrow">{esc(h.hypothesis_id)} · 研究假设</span><span class="badge">{'实验受阻' if gate['gaps'] else '待人工实验审查'}</span></div><h2>{esc(h.title)}</h2><p>{esc(h.question)}</p><div class="facts"><div><small>靶点 / 作用方向</small>{esc(h.target)} / {esc(h.direction)}</div><div><small>适应症 / 形式</small>{esc(h.indication)} / {esc(h.modality)}</div><div><small>目标人群</small>{esc(h.population)}</div></div><p><b>待验证差异：</b>{esc(h.differentiation_to_test)}</p><p class="meta">{gate['independent_source_families']} 个来源家族 · {gate['reviewed_support_families']} 个经人工核对的科学支持家族 · {gate['opposing_families']} 个反证家族</p><details open><summary>进入实验前的缺口（{len(gate['gaps'])}）</summary><ul>{gaps or '<li>结构条件齐备，仍需具名人工决定。</li>'}</ul></details><details><summary>支持、反证与来源</summary>{''.join(links)}</details><details><summary>直接比较与 MNC 资产背景</summary><div class="scroll"><table><thead><tr><th>公司</th><th>资产</th><th>事件</th><th>金额口径</th></tr></thead><tbody>{comps}</tbody></table></div><p>这些是比较对象和市场信号；不代表买方对本假设已有兴趣。</p></details><details><summary>实验草案与替代解释</summary><p>{esc(e.question)}</p><h3>需要区分的解释</h3>{ul(h.alternatives)}<dl>{''.join('<dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd>' for k,v in expfields)}</dl><h3>对照</h3>{ul(e.controls)}<h3>质量与停止条件</h3>{ul(e.qc_and_stop)}</details></article>''')
    catalogrows=''.join(f'<tr class="asset" data-search="{esc(r["company"]+" "+r["asset"]+" "+r["mechanism_modality"])}"><td>{esc(r["id"])}</td><td>{esc(r["company"])}</td><td><a href="{esc(r["source_url"])}" target="_blank" rel="noopener noreferrer">{esc(r["asset"])}</a></td><td>{esc(r["evidence_date"])}</td><td>{esc(r["stage_at_cited_source"])}</td><td>{esc(r["limitation"])}</td></tr>' for r in catalog['records'])
    return '''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; base-uri 'none'; form-action 'none'"><title>Virtual Biotech · 资产研究工作台</title><style>
:root{color-scheme:light;--ink:#182c32;--muted:#52676e;--teal:#076b66;--line:#d7e1e0}*{box-sizing:border-box}body{margin:0;background:#f2f5f3;color:var(--ink);font:15px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{background:#163c40;color:white;padding:36px max(24px,calc((100vw - 1180px)/2))}h1{font-size:32px;line-height:1.3;margin:8px 0 12px}header p{color:#d2e1df;margin:0}.eyebrow{text-transform:uppercase;font-size:12px;letter-spacing:1px}main{max-width:1228px;margin:auto;padding:24px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.stat{background:white;border:1px solid var(--line);border-radius:12px;padding:18px}.stat strong{display:block;font-size:28px;color:var(--teal)}.notice{border-left:4px solid #b8852b;background:#fff8e9;padding:14px 18px;margin:22px 0}.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:20px 0}input{font:inherit;padding:12px;border:1px solid #9cafae;border-radius:8px;width:min(100%,460px)}a{color:var(--teal);overflow-wrap:anywhere}.button{display:inline-block;padding:10px 16px;border:1px solid var(--line);border-radius:8px;background:white;text-decoration:none}.candidate{background:white;border:1px solid var(--line);border-radius:14px;padding:24px;margin:20px 0}.card-head{display:flex;justify-content:space-between;gap:12px}.badge{background:#fff0d8;color:#805511;padding:4px 12px;border-radius:20px;font-size:13px}h2{font-size:23px;margin:12px 0}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;padding:18px;background:#f4f7f6;border-radius:8px}.facts small{display:block;color:var(--muted)}.meta{color:var(--muted);font-size:13px}details{border-top:1px solid var(--line);padding:14px 0}summary{cursor:pointer;font-weight:600}li{margin:6px 0}code{overflow-wrap:anywhere;font-size:12px}.evidence{margin:14px 0;padding:16px;background:#f5f7f7;border-left:3px solid #6b9190}.oppose{border-color:#a75235;background:#fff4ee}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top;min-width:110px}th{background:#e8efed}dl{display:grid;grid-template-columns:140px 1fr;gap:8px}dt{font-weight:600}dd{margin:0;overflow-wrap:anywhere}footer{padding:24px 0;color:var(--muted)}[hidden]{display:none!important}@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}.facts{grid-template-columns:1fr}h1{font-size:26px}main{padding:14px}.candidate{padding:16px}}
</style></head><body><header><div class="eyebrow">VIRTUAL BIOTECH / RESEARCH WORKBENCH</div><h1>资产研究与决策工作台</h1><p>从外部投入信号到可检验假设，保留反证、缺口与每一次决定。</p></header><main>'''+f'''<section class="stats"><div class="stat"><strong>{len(catalog['records'])}</strong>资产 / 项目 / 事件</div><div class="stat"><strong>{len(plan.hypotheses)}</strong>待检验假设</div><div class="stat"><strong>{sum(bool(x['gaps']) for x in evaluation['items'])}</strong>实验条件受阻</div><div class="stat"><strong>待签署</strong>人工科学审查</div></section><div class="notice">本页是不可变版本的只读研究视图。市场交易不能替代科学证据，缺失不能视为阴性。没有自动实验授权或临床用途。后续审查记录使用 CLI 查询，原始页面不会被改写。</div><p class="meta">版本：{esc(snapshot)} · 信息截止：{esc(plan.as_of)} · 数据性质：{esc(plan.evidence_kind)}</p><nav class="toolbar"><a class="button" href="plan.json">查看研究计划 JSON</a><a class="button" href="evaluation.json">查看门禁与缺口 JSON</a><a class="button" href="manifest.json">查看完整性清单</a></nav><label for="hyp-search">筛选研究假设</label><div class="toolbar"><input id="hyp-search" placeholder="搜索靶点、疾病或研究问题"><span id="hyp-count" aria-live="polite">{len(plan.hypotheses)} 个假设</span></div>{''.join(cards)}<section><h2>MNC 资产来源索引</h2><p>阶段与交易口径对应来源日期；本工作台不自动重新检索远程页面。</p><label for="asset-search">筛选资产清单</label><div class="toolbar"><input id="asset-search" placeholder="搜索公司、资产或机制"><span id="asset-count" aria-live="polite">{len(catalog['records'])} 条记录</span></div><div class="scroll"><table><thead><tr><th>ID</th><th>公司</th><th>资产 / 项目</th><th>来源日期</th><th>来源时点阶段</th><th>局限</th></tr></thead><tbody>{catalogrows}</tbody></table></div></section><footer>来源元数据已冻结；外部全文不在本包中。请先运行 portfolio verify 检查文件与本机注册表锚点。人工姓名与权利引用是本地自我声明，不是认证。</footer></main>'''+'''<script>
function filter(input,selector,count,noun){const q=input.value.toLocaleLowerCase();let n=0;document.querySelectorAll(selector).forEach(el=>{el.hidden=!el.dataset.search.toLocaleLowerCase().includes(q);if(!el.hidden)n++});document.getElementById(count).textContent=n+' '+noun}
document.getElementById('hyp-search').addEventListener('input',e=>filter(e.target,'.candidate','hyp-count','个假设'));document.getElementById('asset-search').addEventListener('input',e=>filter(e.target,'.asset','asset-count','条记录'));
</script></body></html>'''
